### ISSUE TITLE
modules data

### ISSUE THREAD

**Issue by abhishekgupta92** [liberry-edu/platform#2]
current output is
`{
    "id": 1,
    "name": "Agriculture",
    "description": null,
    "status": "active",
    "created_at": "2016-06-19T18:44:47.000Z",
    "updated_at": "2016-06-19T18:44:47.000Z"
  },`

expected output is
`{
          'id': '9023',
          'name': 'Agriculture',
          'description': 'Learn about farming',
          'image': 'images/bl1.jpg',
          'media_consumed': 3,
          'media_total': 9,
},
`

add media_consumed and media_total from the server to the api call.

**Comment by vaibhav-sinha** [comment]
'media_consumed' can only be provided when user activity tracking is enabled. Are you adding that in the current version?
